<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 ./public/assets/gltf/unt.glb -t
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  ref = new Group()

  type ActionName = 'TAction' | 'UAction' | 'NAction'
  type GLTFResult = {
    nodes: {
      T: THREE.Mesh
      U: THREE.Mesh
      N: THREE.Mesh
    }
    materials: {
      ['Material.001']: THREE.MeshPhysicalMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/public/assets/gltf/unt.glb')

  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)
</script>

<T
  is={ref}
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Scene">
      <T.Mesh
        name="T"
        geometry={gltf.nodes.T.geometry}
        material={gltf.materials['Material.001']}
        position={[0, 5, 0]}
      />
      <T.Mesh
        name="U"
        geometry={gltf.nodes.U.geometry}
        material={gltf.materials['Material.001']}
        position={[0, 5, 0]}
      />
      <T.Mesh
        name="N"
        geometry={gltf.nodes.N.geometry}
        material={gltf.materials['Material.001']}
        position={[0, 5, 0]}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
