<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 ./public/assets/gltf/greenman.glb -t
-->

<script lang="ts">
  import type * as THREE from 'three';
  import { Group } from 'three';
  import type { Snippet } from 'svelte';
  import { T, type Props } from '@threlte/core';
  import { useGltf, useGltfAnimations } from '@threlte/extras';
  import { MeshToonMaterial } from 'three';
  import { CameraAnimationSettings } from './cameraAnimation.svelte.ts';

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group;
    children?: Snippet<[{ ref: THREE.Group }]>;
    fallback?: Snippet;
    error?: Snippet<[{ error: Error }]>;
  } = $props();

  ref = new Group();

  type ActionName = 'CameraAction';
  type GLTFResult = {
    nodes: {
      green: THREE.Mesh;
      white: THREE.Mesh;
      black: THREE.Mesh;
      Plane: THREE.Mesh;
    };
    materials: {
      green: THREE.MeshPhysicalMaterial;
      white: THREE.MeshStandardMaterial;
      black: THREE.MeshStandardMaterial;
    };
  };

  const toonMaterial = {
    green: new MeshToonMaterial({ color: 0x00dd00 }),
    white: new MeshToonMaterial({ color: 0xffffff }),
    black: new MeshToonMaterial({ color: 0x333333 }),
  };

  const gltf = useGltf<GLTFResult>(`${import.meta.env.BASE_URL}assets/gltf/greenman2.glb`);
  let materials = $derived($gltf?.materials);

  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref);

  let materialGreen = $derived(CameraAnimationSettings.isToonMaterial ? toonMaterial.green : materials?.green);
  let materialWhite = $derived(CameraAnimationSettings.isToonMaterial ? toonMaterial.white : materials?.white);
  let materialBlack = $derived(CameraAnimationSettings.isToonMaterial ? toonMaterial.black : materials?.black);
</script>

<T is={ref} dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Scene">
      <T.PerspectiveCamera
        name="Camera"
        makeDefault={true}
        far={1000}
        near={0.1}
        fov={22.9}
        position={[0, 1.29, 1.25]}
      />
      <T.Mesh
        name="green"
        geometry={gltf.nodes.green.geometry}
        material={materialGreen}
        position={[0, 0.43, -1]}
        rotation={[0.19, Math.PI / 2, 0]}
      />
      <T.Mesh
        name="white"
        geometry={gltf.nodes.white.geometry}
        material={materialWhite}
        position={[0, 2.68, 0.11]}
        rotation={[Math.PI / 2, 0, -0.14]}
        scale={0.16}
      />
      <T.Mesh
        name="black"
        geometry={gltf.nodes.black.geometry}
        material={materialBlack}
        position={[0, 2.68, 0.11]}
        rotation={[Math.PI / 2, 0, -0.14]}
        scale={0.16}
      />
      <!-- <T.Mesh name="Plane" geometry={gltf.nodes.Plane.geometry} material={gltf.nodes.Plane.material} scale={18.1} /> -->
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
